---

- name: config > Template
  template:
    src: "{{ manala_keepalived_config_template|ternary(manala_keepalived_config_template, 'config/empty.j2') }}"
    dest: "{{ manala_keepalived_config_file }}"
    owner: root
    group: root
    mode: "0644"
  when: (manala_keepalived_config_template is not none) or (manala_keepalived_config|length)
  notify:
    - keepalived reload
