---

- name: environment > Template
  template:
    src: "{{ manala_keepalived_environment_template|ternary(manala_keepalived_environment_template, 'environment/default.j2') }}"
    dest: "{{ manala_keepalived_environment_file }}"
    owner: root
    group: root
    mode: "0644"
  when: (manala_keepalived_environment_template is not none) or (manala_keepalived_environment|length)
  notify:
    - keepalived restart
